### ISSUE TITLE
IGW-Mod using wrong subfolder when viewing block from different mod

### ISSUE THREAD

**Issue by blockbreaker1361** [Keridos/FloodLights#38] opened 2015-07-20 22:13 UTC
I'm not getting any info on the IGW mod. Here is pic for proof. Both mods are latest versions.
http://imgur.com/Zeki5E5

**Comment by Keridos** [comment] 2015-07-20 22:14
Update your igwmod, I think you use an old version of it.

**Comment by blockbreaker1361** [comment] 2015-07-20 22:15
I'm using latest version of both mods.

**Comment by Keridos** [comment] 2015-07-20 22:52
This seeems to be caused by IGWmod.

**Comment by Keridos** [comment] 2015-07-26 00:37
Is fixed in igwmod 1.1.7-26. Also updated igwmod compatability again, so everything runs smooth with the new version.

**Closed by Keridos** 2015-07-26 00:37 UTC
Labels: external bug, wontfix
